<?xml version="1.0"?>
<package format="2">
    <name>open3d_rosbag_mapper_mesher</name>
    <version>0.0.0</version>
    <description>Open3D map and mesh generation</description>

    <!-- Maintainer -->
    <maintainer email="nubertj@ethz.ch">Julian Nubert</maintainer>
    <author email="nubertj@ethz.ch">Edo Jelavic</author>

    <!-- License -->
    <license>BSD-3-Clause</license>

    <!-- Dependencies -->
    <buildtool_depend>catkin</buildtool_depend>
    <depend>roscpp</depend>
    <depend>roslib</depend>
    <depend>open3d_conversions</depend>
    <depend>open3d_slam</depend>
    <depend>open3d_slam_ros</depend>
    <depend>eigen_conversions</depend>
    <depend>tf</depend>
    <depend>tf2</depend>
    <depend>tf2_msgs</depend>
    <depend>tf2_ros</depend>
    <depend>tf2_geometry_msgs</depend>
    <depend>interactive_markers</depend>
    <depend>rosbag</depend>
    <depend>open3d_slam_lua_io</depend>

</package>
