<?xml version="1.0"?>
<package format="3">
  <name>open3d_colcon</name>
  <version>0.0.0</version>
  <description>Open3D wrapper for colcon workspaces</description>

  <maintainer email="jelavice@ethz.ch">Edo Jelavic</maintainer>

  <license>BSD-3-Clause</license>

  <author email="jelavice@ethz.ch">Edo Jelavic</author>
  <author email="nubertj@ethz.ch">Julian Nubert</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
